# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.18.4-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.18.4-Linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ayan/relaxase

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ayan/relaxase

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.18.4-Linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.18.4-Linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayan/relaxase/CMakeFiles /home/ayan/relaxase//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayan/relaxase/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named relaxase

# Build rule for target.
relaxase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 relaxase
.PHONY : relaxase

# fast build rule for target.
relaxase/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/build
.PHONY : relaxase/fast

#=============================================================================
# Target rules for targets named tiny-aes

# Build rule for target.
tiny-aes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tiny-aes
.PHONY : tiny-aes

# fast build rule for target.
tiny-aes/fast:
	$(MAKE) $(MAKESILENT) -f lib/tiny-AES-c/CMakeFiles/tiny-aes.dir/build.make lib/tiny-AES-c/CMakeFiles/tiny-aes.dir/build
.PHONY : tiny-aes/fast

#=============================================================================
# Target rules for targets named schifra

# Build rule for target.
schifra: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 schifra
.PHONY : schifra

# fast build rule for target.
schifra/fast:
	$(MAKE) $(MAKESILENT) -f lib/schifra_dir/CMakeFiles/schifra.dir/build.make lib/schifra_dir/CMakeFiles/schifra.dir/build
.PHONY : schifra/fast

src/dna_block.o: src/dna_block.cpp.o

.PHONY : src/dna_block.o

# target to build an object file
src/dna_block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_block.cpp.o
.PHONY : src/dna_block.cpp.o

src/dna_block.i: src/dna_block.cpp.i

.PHONY : src/dna_block.i

# target to preprocess a source file
src/dna_block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_block.cpp.i
.PHONY : src/dna_block.cpp.i

src/dna_block.s: src/dna_block.cpp.s

.PHONY : src/dna_block.s

# target to generate assembly for a file
src/dna_block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_block.cpp.s
.PHONY : src/dna_block.cpp.s

src/dna_decoder.o: src/dna_decoder.cpp.o

.PHONY : src/dna_decoder.o

# target to build an object file
src/dna_decoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_decoder.cpp.o
.PHONY : src/dna_decoder.cpp.o

src/dna_decoder.i: src/dna_decoder.cpp.i

.PHONY : src/dna_decoder.i

# target to preprocess a source file
src/dna_decoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_decoder.cpp.i
.PHONY : src/dna_decoder.cpp.i

src/dna_decoder.s: src/dna_decoder.cpp.s

.PHONY : src/dna_decoder.s

# target to generate assembly for a file
src/dna_decoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_decoder.cpp.s
.PHONY : src/dna_decoder.cpp.s

src/dna_library.o: src/dna_library.cpp.o

.PHONY : src/dna_library.o

# target to build an object file
src/dna_library.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_library.cpp.o
.PHONY : src/dna_library.cpp.o

src/dna_library.i: src/dna_library.cpp.i

.PHONY : src/dna_library.i

# target to preprocess a source file
src/dna_library.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_library.cpp.i
.PHONY : src/dna_library.cpp.i

src/dna_library.s: src/dna_library.cpp.s

.PHONY : src/dna_library.s

# target to generate assembly for a file
src/dna_library.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_library.cpp.s
.PHONY : src/dna_library.cpp.s

src/dna_patch.o: src/dna_patch.cpp.o

.PHONY : src/dna_patch.o

# target to build an object file
src/dna_patch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_patch.cpp.o
.PHONY : src/dna_patch.cpp.o

src/dna_patch.i: src/dna_patch.cpp.i

.PHONY : src/dna_patch.i

# target to preprocess a source file
src/dna_patch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_patch.cpp.i
.PHONY : src/dna_patch.cpp.i

src/dna_patch.s: src/dna_patch.cpp.s

.PHONY : src/dna_patch.s

# target to generate assembly for a file
src/dna_patch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_patch.cpp.s
.PHONY : src/dna_patch.cpp.s

src/dna_pool.o: src/dna_pool.cpp.o

.PHONY : src/dna_pool.o

# target to build an object file
src/dna_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_pool.cpp.o
.PHONY : src/dna_pool.cpp.o

src/dna_pool.i: src/dna_pool.cpp.i

.PHONY : src/dna_pool.i

# target to preprocess a source file
src/dna_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_pool.cpp.i
.PHONY : src/dna_pool.cpp.i

src/dna_pool.s: src/dna_pool.cpp.s

.PHONY : src/dna_pool.s

# target to generate assembly for a file
src/dna_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_pool.cpp.s
.PHONY : src/dna_pool.cpp.s

src/dna_sector.o: src/dna_sector.cpp.o

.PHONY : src/dna_sector.o

# target to build an object file
src/dna_sector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_sector.cpp.o
.PHONY : src/dna_sector.cpp.o

src/dna_sector.i: src/dna_sector.cpp.i

.PHONY : src/dna_sector.i

# target to preprocess a source file
src/dna_sector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_sector.cpp.i
.PHONY : src/dna_sector.cpp.i

src/dna_sector.s: src/dna_sector.cpp.s

.PHONY : src/dna_sector.s

# target to generate assembly for a file
src/dna_sector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_sector.cpp.s
.PHONY : src/dna_sector.cpp.s

src/dna_strand.o: src/dna_strand.cpp.o

.PHONY : src/dna_strand.o

# target to build an object file
src/dna_strand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_strand.cpp.o
.PHONY : src/dna_strand.cpp.o

src/dna_strand.i: src/dna_strand.cpp.i

.PHONY : src/dna_strand.i

# target to preprocess a source file
src/dna_strand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_strand.cpp.i
.PHONY : src/dna_strand.cpp.i

src/dna_strand.s: src/dna_strand.cpp.s

.PHONY : src/dna_strand.s

# target to generate assembly for a file
src/dna_strand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_strand.cpp.s
.PHONY : src/dna_strand.cpp.s

src/dna_test.o: src/dna_test.cpp.o

.PHONY : src/dna_test.o

# target to build an object file
src/dna_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_test.cpp.o
.PHONY : src/dna_test.cpp.o

src/dna_test.i: src/dna_test.cpp.i

.PHONY : src/dna_test.i

# target to preprocess a source file
src/dna_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_test.cpp.i
.PHONY : src/dna_test.cpp.i

src/dna_test.s: src/dna_test.cpp.s

.PHONY : src/dna_test.s

# target to generate assembly for a file
src/dna_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/dna_test.cpp.s
.PHONY : src/dna_test.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/relaxase.o: src/relaxase.cpp.o

.PHONY : src/relaxase.o

# target to build an object file
src/relaxase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/relaxase.cpp.o
.PHONY : src/relaxase.cpp.o

src/relaxase.i: src/relaxase.cpp.i

.PHONY : src/relaxase.i

# target to preprocess a source file
src/relaxase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/relaxase.cpp.i
.PHONY : src/relaxase.cpp.i

src/relaxase.s: src/relaxase.cpp.s

.PHONY : src/relaxase.s

# target to generate assembly for a file
src/relaxase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/relaxase.cpp.s
.PHONY : src/relaxase.cpp.s

src/relaxase_client.o: src/relaxase_client.cpp.o

.PHONY : src/relaxase_client.o

# target to build an object file
src/relaxase_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/relaxase_client.cpp.o
.PHONY : src/relaxase_client.cpp.o

src/relaxase_client.i: src/relaxase_client.cpp.i

.PHONY : src/relaxase_client.i

# target to preprocess a source file
src/relaxase_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/relaxase_client.cpp.i
.PHONY : src/relaxase_client.cpp.i

src/relaxase_client.s: src/relaxase_client.cpp.s

.PHONY : src/relaxase_client.s

# target to generate assembly for a file
src/relaxase_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/relaxase_client.cpp.s
.PHONY : src/relaxase_client.cpp.s

src/relaxase_configuration.o: src/relaxase_configuration.cpp.o

.PHONY : src/relaxase_configuration.o

# target to build an object file
src/relaxase_configuration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/relaxase_configuration.cpp.o
.PHONY : src/relaxase_configuration.cpp.o

src/relaxase_configuration.i: src/relaxase_configuration.cpp.i

.PHONY : src/relaxase_configuration.i

# target to preprocess a source file
src/relaxase_configuration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/relaxase_configuration.cpp.i
.PHONY : src/relaxase_configuration.cpp.i

src/relaxase_configuration.s: src/relaxase_configuration.cpp.s

.PHONY : src/relaxase_configuration.s

# target to generate assembly for a file
src/relaxase_configuration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/relaxase.dir/build.make CMakeFiles/relaxase.dir/src/relaxase_configuration.cpp.s
.PHONY : src/relaxase_configuration.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... relaxase"
	@echo "... schifra"
	@echo "... tiny-aes"
	@echo "... src/dna_block.o"
	@echo "... src/dna_block.i"
	@echo "... src/dna_block.s"
	@echo "... src/dna_decoder.o"
	@echo "... src/dna_decoder.i"
	@echo "... src/dna_decoder.s"
	@echo "... src/dna_library.o"
	@echo "... src/dna_library.i"
	@echo "... src/dna_library.s"
	@echo "... src/dna_patch.o"
	@echo "... src/dna_patch.i"
	@echo "... src/dna_patch.s"
	@echo "... src/dna_pool.o"
	@echo "... src/dna_pool.i"
	@echo "... src/dna_pool.s"
	@echo "... src/dna_sector.o"
	@echo "... src/dna_sector.i"
	@echo "... src/dna_sector.s"
	@echo "... src/dna_strand.o"
	@echo "... src/dna_strand.i"
	@echo "... src/dna_strand.s"
	@echo "... src/dna_test.o"
	@echo "... src/dna_test.i"
	@echo "... src/dna_test.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/relaxase.o"
	@echo "... src/relaxase.i"
	@echo "... src/relaxase.s"
	@echo "... src/relaxase_client.o"
	@echo "... src/relaxase_client.i"
	@echo "... src/relaxase_client.s"
	@echo "... src/relaxase_configuration.o"
	@echo "... src/relaxase_configuration.i"
	@echo "... src/relaxase_configuration.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

